name: napari-chromosome-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - sphinx>=4.0.0
  - sphinx_rtd_theme>=1.0.0
  - myst-parser>=0.18.0
  - numpy>=1.20.0
  - scipy>=1.7.0
  - pandas>=1.3.0
  - scikit-image>=0.18.0
  - matplotlib>=3.3.0
  - pillow>=8.0.0
  - pip
  - pip:
    - napari>=0.4.0
    - cellpose>=2.0.0
    - magicgui>=0.5.0
    - qtpy>=2.0.0
    - superqt>=0.3.0 